name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Run tests
      run: task test-ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m
        skip-cache: true
        
    - name: Run lint
      run: task lint

  validate-config:
    name: Validate Configuration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Validate configs/domains.json
      run: task validate-config

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint, validate-config]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        
    - name: Build application
      run: task build-ci
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hntop-rss-binary
        path: build/hntop-rss
        retention-days: 7