name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      major_version:
        description: 'Major version number'
        required: true
        default: '1'
        type: string

env:
  MAJOR_VERSION: ${{ github.event.inputs.major_version || '1' }}

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run tests
        run: task test-ci

      - name: Run linter
        run: task lint

      - name: Validate config
        run: task validate-config

  build-and-release:
    name: Build and Release
    needs: test-and-lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Set version
        id: version
        run: |
          VERSION="${{ env.MAJOR_VERSION }}.${{ github.run_number }}-$(git rev-parse --short HEAD)"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "TAG=v${{ env.MAJOR_VERSION }}.${{ github.run_number }}" >> $GITHUB_ENV
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=v${{ env.MAJOR_VERSION }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build for Linux AMD64
        run: VERSION=${{ env.VERSION }} task build-linux-amd64

      - name: Build for Darwin AMD64
        run: VERSION=${{ env.VERSION }} task build-darwin-amd64

      - name: Build for Darwin ARM64
        run: VERSION=${{ env.VERSION }} task build-darwin-arm64

      - name: Build for Windows AMD64
        run: VERSION=${{ env.VERSION }} task build-windows

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          generate_release_notes: true
          files: |
            build/hntop-rss-linux-amd64
            build/hntop-rss-darwin-amd64
            build/hntop-rss-darwin-arm64
            build/hntop-rss-windows-amd64.exe
          body: |
            ## hntop-rss ${{ steps.version.outputs.version }}
            
            Automated release built from commit ${{ github.sha }}
            
            ### Downloads
            - **Linux (AMD64)**: `hntop-rss-linux-amd64`
            - **macOS (Intel)**: `hntop-rss-darwin-amd64`
            - **macOS (Apple Silicon)**: `hntop-rss-darwin-arm64`
            - **Windows (AMD64)**: `hntop-rss-windows-amd64.exe`
            
            ### Usage
            ```bash
            ./hntop-rss-linux-amd64 -outdir /path/to/output -min-points 50
            ```